# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      # run tests!
      - run: npm run lint
  deploy:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "00:e0:7a:72:c7:e3:5b:0d:61:3f:35:e5:f5:d1:b7:db"
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            apt-get update && apt-get install -yq libgconf-2-4
            apt-get update && apt-get install -y wget --no-install-recommends \
            && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
            && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
            && apt-get update \
            && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
            --no-install-recommends \
            && rm -rf /var/lib/apt/lists/* \
            && apt-get purge --auto-remove -y curl \
            && rm -rf /src/*.deb
      - run: npm install
      - run:
          name: Deploy Application to Github Pages
          command: |
            git config --global user.email "ci@estudiomanati.com"
            git config --global user.name "CI Bot"
            git config --global push.default simple
            git clone git@github.com:fdicr-nmd/fdicr-nmd.github.io.git
            rm -r fdicr-nmd.github.io/*
            npm run build
            cp -R dist/* fdicr-nmd.github.io/
            cd fdicr-nmd.github.io
            git add -A
            git commit -m "Update compiled site"
            git push
workflows:
  version: 2
  build-deploys:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy-hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - deploy-hold
